name: Suicide_Barbie

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Checkout the latest PSP toolchain script
      run: |
        git clone https://github.com/pspdev/psptoolchain.git

    - name: Retrieve commit hash
      id: psptoolchain
      run: echo "::set-output name=sha::$(git -C psptoolchain rev-parse HEAD)"
        
    - name: Cache PSP toolchain
      uses: actions/cache@v2
      id: cache-psptoolchain
      with:
        path: pspdev
        key: ${{ runner.os }}-psptoolchain-${{ steps.psptoolchain.outputs.sha }}

    - name: Install deps
      if: steps.cache-psptoolchain.outputs.cache-hit != 'true'
      run: |
        ./prepare-debian-ubuntu.sh

    - name: Bootstrap
      if: steps.cache-psptoolchain.outputs.cache-hit != 'true'
      run: |
        export PSPDEV=$(pwd)/pspdev
        export PATH=$PATH:$PSPDEV/bin
        cd psptoolchain
        ./toolchain.sh

    - name: Clean
      run: |
        ./clean.sh

    - name: Build
      run: |
        ./build.sh
